repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: mongodb
    namespace: data
    chart: bitnami/mongodb
    version: 15.6.0
    values:
      - auth:
          enabled: true
          rootPassword: password
        persistence:
          enabled: true
