apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-app
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: node-app
  namespaceSelector:
    matchNames:
      - apps
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
