apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-demo
  template:
    metadata:
      labels:
        app: private-demo
    spec:
      imagePullSecrets:
        - name: ecr-regcred
      containers:
        - name: private-demo
          # Replace with your real ECR image URI, e.g.:
          # <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/private-demo:1.0
          image: IMAGE_URI_PLACEHOLDER
          ports:
            - containerPort: 8080
