apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myapp-eks
  region: eu-north-1
  version: "1.29"

iam:
  withOIDC: true

managedNodeGroups:
  - name: ng-default
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
