plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  instance-state-name: running
  tag:project: configuration-management-ansible
  tag:Role:
    - ansible-control
    - ansible-managed
    - nexus
    - jenkins

keyed_groups:
  - key: tags.Role
    prefix: role
  - key: tags.Name
    prefix: name

compose:
  ansible_host: private_ip_address
