pipeline {
  agent any

  environment {
    REGISTRY = "165.22.127.6:8083"
    IMAGE = "module8-demo"
    TAG = "${BUILD_NUMBER}"
  }

  stages {

    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build Image') {
      steps {
        sh '''
          cd module-8-jenkins-ci-cd/app
          docker build -t ${IMAGE}:${TAG} .
          docker tag ${IMAGE}:${TAG} ${REGISTRY}/${IMAGE}:${TAG}
        '''
      }
    }

    stage('Push to Nexus') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'nexus-docker-creds',
          usernameVariable: 'NEXUS_USER',
          passwordVariable: 'NEXUS_PASS'
        )]) {
          sh 'echo "$NEXUS_PASS" | docker login $REGISTRY -u "$NEXUS_USER" --password-stdin'
        }
        sh "docker push ${REGISTRY}/${IMAGE}:${TAG}"
      }
    }
  }

  post {
    success { echo "✅ Module 8 pipeline completed successfully" }
    failure { echo "❌ Module 8 pipeline failed" }
  }
}
